#!/usr/bin/env bash
# script that pings an IP address passed as an argument.
if [ $# -eq 0 ]; then
  echo "Usage: $0 {IP_ADDRESS}"
  exit 1
fi

ip_address="$1"

ping_result=$(ping -c 5 "$ip_address" 2>&1)

if [[ $? -eq 0 ]]; then
  echo "$ping_result" | awk '/PING|bytes from/ {print} /rtt/ {print "   ---", $0}'
else
  echo "Ping failed for $ip_address"
fi
