#!/usr/bin/env bash
# script that pings an IP address passed as an argument.
if [ $# -eq 0 ]; then
  echo "Usage: $0 {IP_ADDRESS}"
  exit 1
fi

ip_address="$1"

if ping -c 5 "$ip_address" >/dev/null; then
  ping -c 5 "$ip_address" | awk '/PING|bytes from/ {print} /rtt/ {print "   ---", $0}'
else
  echo "Ping failed for $ip_address"
fi
